// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pump-dashboard/Analytics.tsx": () => import("../components/mockups/pump-dashboard/Analytics.tsx"),
  "./components/mockups/pump-dashboard/Overview.tsx": () => import("../components/mockups/pump-dashboard/Overview.tsx"),
  "./components/mockups/pump-dashboard/Predict.tsx": () => import("../components/mockups/pump-dashboard/Predict.tsx"),
  "./components/mockups/pump-dashboard/Reports.tsx": () => import("../components/mockups/pump-dashboard/Reports.tsx")
};
