"""characterize_train_csv.py — Phase 0 of the pump-to-engine migration
(docs/plan/2026-08-26-pump-to-engine-migration.md).

Reads data/train.csv and computes, per column: percentile bands (for
engine-physics.yaml hard/operating ranges), the pairwise correlation
matrix (gates validator.py rules R2-R4), and Engine_Condition
class-conditional statistics (resolves label polarity — §5 of the plan).

Writes docs/analysis/2026-08-26-train-csv-characterization.md. Every
numeric constant used later in the migration (Phases 1, 3, 7) must trace
back to this artifact rather than being hand-guessed.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parent.parent
TRAIN_CSV = REPO_ROOT / "data" / "train.csv"
OUT_MD = REPO_ROOT / "docs" / "analysis" / "2026-08-26-train-csv-characterization.md"

METRIC_COLUMNS = [
    "Engine_RPM",
    "Lub_Oil_Pressure",
    "Fuel_Pressure",
    "Coolant_Pressure",
    "Lub_Oil_Temperature",
    "Coolant_Temperature",
]
LABEL_COLUMN = "Engine_Condition"

PERCENTILES = [0.1, 1, 5, 25, 50, 75, 95, 99, 99.9]


def characterize(df: pd.DataFrame) -> dict:
    result: dict = {"rowCount": len(df), "duplicateRows": int(df.duplicated().sum())}
    result["nullCounts"] = {c: int(df[c].isna().sum()) for c in METRIC_COLUMNS + [LABEL_COLUMN]}

    per_column = {}
    for col in METRIC_COLUMNS:
        s = df[col].astype(float)
        q = {f"p{p}": float(np.percentile(s, p)) for p in PERCENTILES}
        iqr = q["p75"] - q["p25"]
        # Widened, not just percentile-derived: the §2.3 invariant requires hard
        # bounds to strictly contain every observed row, so take the wider of the
        # percentile-based estimate and the observed extreme itself (with a small
        # margin so a bound isn't pinned exactly to one data point).
        hard_min = max(0.0, min(q["p0.1"] - 1.5 * iqr, float(s.min()) - 0.05 * iqr))
        hard_max = max(q["p99.9"] + 1.5 * iqr, float(s.max()) + 0.05 * iqr)
        per_column[col] = {
            "min": float(s.min()),
            "max": float(s.max()),
            "mean": float(s.mean()),
            "median": float(s.median()),
            "std": float(s.std()),
            "iqr": float(iqr),
            **q,
            "proposedHardMin": float(hard_min),
            "proposedHardMax": float(hard_max),
            "proposedOperatingMin": q["p1"],
            "proposedOperatingMax": q["p99"],
            # invariant check: hard bounds must contain observed extremes (§2.3)
            "hardBoundsContainObserved": bool(hard_min <= s.min() and hard_max >= s.max()),
        }
    result["perColumn"] = per_column

    corr = df[METRIC_COLUMNS].corr(method="pearson")
    result["correlationMatrix"] = corr.round(4).to_dict()

    class_counts = df[LABEL_COLUMN].value_counts().to_dict()
    result["classBalance"] = {str(k): int(v) for k, v in class_counts.items()}

    class_means = df.groupby(LABEL_COLUMN)[METRIC_COLUMNS].mean()
    result["classConditionalMeans"] = {
        col: {str(k): float(v) for k, v in vals.items()}
        for col, vals in class_means.round(4).to_dict().items()
    }

    # single-column separation: for each metric, what fraction of each
    # class falls outside that metric's global p5/p95 band (extremity as
    # a crude single-column AUC proxy without needing sklearn here).
    separation = {}
    for col in METRIC_COLUMNS:
        p5, p95 = np.percentile(df[col].astype(float), [5, 95])
        frac_by_class = df.groupby(LABEL_COLUMN)[col].apply(
            lambda s2, lo=p5, hi=p95: float(((s2 < lo) | (s2 > hi)).mean())
        )
        separation[col] = {str(k): float(v) for k, v in frac_by_class.items()}
    result["extremityFractionByClass"] = separation

    return result


def render_markdown(stats: dict) -> str:
    lines = []
    lines.append("# Phase 0: `data/train.csv` Empirical Characterization")
    lines.append("")
    lines.append("**Date:** 2026-08-26")
    lines.append(
        "**Generated by:** `scripts/characterize_train_csv.py` — re-run this script "
        "to regenerate this file if `data/train.csv` changes."
    )
    lines.append(
        "**Purpose:** ground truth for every numeric constant used in "
        "`docs/plan/2026-08-26-pump-to-engine-migration.md` Phases 1-8. "
        "No range, threshold, or physics rule in that plan should be hand-guessed "
        "once this document exists."
    )
    lines.append("")

    lines.append("## Dataset summary")
    lines.append("")
    lines.append(f"- Row count: {stats['rowCount']}")
    lines.append(f"- Duplicate rows: {stats['duplicateRows']}")
    lines.append(f"- Null counts: `{json.dumps(stats['nullCounts'])}`")
    lines.append("")

    lines.append("## Per-column statistics and proposed ranges")
    lines.append("")
    lines.append(
        "Hard bounds = `max(0, p0.1 - 1.5*IQR)` to `p99.9 + 1.5*IQR` (plan §2.3 rule). "
        "Operating range = p1-p99. **`hardBoundsContainObserved` must be `True` for every "
        "row — this is the plan's §2.3 invariant; if any row is `False`, the hard-bound "
        "formula must be widened before use in `engine-physics.yaml`.**"
    )
    lines.append("")
    lines.append(
        "| Column | min | max | mean | median | std | p1 | p5 | p95 | p99 | "
        "Proposed hard min | Proposed hard max | Proposed operating min | "
        "Proposed operating max | Bounds contain observed |"
    )
    lines.append("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    for col, s in stats["perColumn"].items():
        lines.append(
            f"| `{col}` | {s['min']:.3f} | {s['max']:.3f} | {s['mean']:.3f} | "
            f"{s['median']:.3f} | {s['std']:.3f} | {s['p1']:.3f} | {s['p5']:.3f} | "
            f"{s['p95']:.3f} | {s['p99']:.3f} | {s['proposedHardMin']:.3f} | "
            f"{s['proposedHardMax']:.3f} | {s['proposedOperatingMin']:.3f} | "
            f"{s['proposedOperatingMax']:.3f} | {s['hardBoundsContainObserved']} |"
        )
    lines.append("")

    lines.append("## Pairwise correlation matrix (Pearson)")
    lines.append("")
    lines.append(
        "Gates validator.py cross-variable rules R2-R4 (plan §4.1): a rule is only "
        "implemented if the columns it relates show real correlation here. |r| < ~0.15 "
        "is treated as effectively uncorrelated for this purpose."
    )
    lines.append("")
    cols = list(stats["correlationMatrix"].keys())
    header = "| | " + " | ".join(f"`{c}`" for c in cols) + " |"
    sep = "|---|" + "---|" * len(cols)
    lines.append(header)
    lines.append(sep)
    for row_col in cols:
        row = stats["correlationMatrix"][row_col]
        vals = " | ".join(f"{row[c]:.3f}" for c in cols)
        lines.append(f"| `{row_col}` | {vals} |")
    lines.append("")

    lines.append("## `Engine_Condition` class balance")
    lines.append("")
    lines.append(f"`{json.dumps(stats['classBalance'])}`")
    lines.append("")

    lines.append("## Class-conditional means (resolves label polarity — plan §5)")
    lines.append("")
    lines.append(
        "For each metric, the mean value within each `Engine_Condition` class. "
        "The class whose means sit further from the population-wide healthy range "
        "(e.g. lower `Lub_Oil_Pressure`, higher `Coolant_Temperature`) is the faulty "
        "class — record that finding explicitly below, do not leave it implicit."
    )
    lines.append("")
    cc_means = stats["classConditionalMeans"]
    class_labels = sorted({k for col_means in cc_means.values() for k in col_means.keys()})
    header = "| Metric | " + " | ".join(f"class={c}" for c in class_labels) + " |"
    sep = "|---|" + "---|" * len(class_labels)
    lines.append(header)
    lines.append(sep)
    for col in METRIC_COLUMNS:
        row = cc_means[col]
        vals = " | ".join(f"{row.get(c, float('nan')):.4f}" for c in class_labels)
        lines.append(f"| `{col}` | {vals} |")
    lines.append("")

    lines.append("## Extremity fraction by class (single-column separation proxy)")
    lines.append("")
    lines.append(
        "Fraction of each class's rows falling outside that column's global p5/p95 band. "
        "If a class is disproportionately outside the band for multiple metrics "
        "simultaneously (especially `Lub_Oil_Pressure` low-side, `Coolant_Temperature` "
        "high-side), that class is the faulty one — cross-check against the "
        "class-conditional means table above before concluding polarity."
    )
    lines.append("")
    ext = stats["extremityFractionByClass"]
    header = "| Metric | " + " | ".join(f"class={c}" for c in class_labels) + " |"
    sep = "|---|" + "---|" * len(class_labels)
    lines.append(header)
    lines.append(sep)
    for col in METRIC_COLUMNS:
        row = ext[col]
        vals = " | ".join(f"{row.get(c, float('nan')):.4f}" for c in class_labels)
        lines.append(f"| `{col}` | {vals} |")
    lines.append("")

    lines.append("## Findings (fill in after reviewing the tables above)")
    lines.append("")
    lines.append("- **Label polarity:** TBD — state which class (0 or 1) is faulty and the evidence.")
    lines.append(
        "- **Validator rules R2-R4 (plan §4.1):** TBD — state which of the proposed "
        "cross-variable rules are supported by the correlation matrix above (|r| >= ~0.15) "
        "and which should be dropped for lack of evidence."
    )
    lines.append(
        "- **Class separability (plan §12 Q2):** TBD — state whether the two classes "
        "are meaningfully separable across the six metrics, or whether Q2's contingency "
        "needs to be invoked."
    )
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    df = pd.read_csv(TRAIN_CSV)
    missing = set(METRIC_COLUMNS + [LABEL_COLUMN]) - set(df.columns)
    if missing:
        raise SystemExit(f"train.csv is missing expected column(s): {sorted(missing)}")

    stats = characterize(df)
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text(render_markdown(stats), encoding="utf-8")
    print(f"Wrote {OUT_MD}")

    # Fail loudly if the §2.3 invariant doesn't hold for any column, since
    # every later phase depends on it.
    bad = [c for c, s in stats["perColumn"].items() if not s["hardBoundsContainObserved"]]
    if bad:
        raise SystemExit(f"Hard-bound invariant violated for: {bad} — widen the formula before proceeding.")


if __name__ == "__main__":
    main()
